# Final Exam

The final test consists of two parts. The first part consists of multiple choice questions available via Moodle. The second consists of coding problems to be solved in this notebook.

You have **90 minutes** to complete the two parts. You are allowed to use the **help/?** function in Python, but **no other sources** (including any previous Jupyter notebook, Google search, Stack Overflow, ChatGPT, etc.).


j<br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br>

----------------

# Part 2:
**Programming tasks<br>(84 points)**

**Please write your code to the Code cell below each question.**

Note: make sure you test your code. You can also run part of your code while you are working on it.

**Q1 (20 points):** An increasing subarray of an integer array is any consecutive sequence of array integers within the original array whose values strictly increase. Write a Python function find_long_subarray(A) which accepts a Python tuple

$A = (a_0, a_1, . . . , a_{n−1})$

of $n$ positive integers, and returns a longest increasing subarray of A, i.e. an increasing subarray with length at least as large as every other increasing subarray. For example, if $A = (1,3,4,2,7,5,6,9,8)$, your program should return either (1,3,4) and (5,6,9).

In [ ]:
#1
def find_long_subarray(A):
    if not A:
        return ()
    n = len(A)
    max_len = 1
    current_len = 1
    max_start_index = 0
    current_start_index = 0
    for i in range(1, n):
        if A[i] > A[i - 1]:
            current_len += 1
        else:
            if current_len > max_len:
                max_len = current_len
                max_start_index = current_start_index
            current_start_index = i
            current_len = 1
    if current_len > max_len:
        max_len = current_len
        max_start_index = current_start_index
    return tuple(A[max_start_index:max_start_index + max_len])
A = (1, 3, 4, 2, 7, 5, 6, 9, 8)
print(find_long_subarray(A))

(1, 3, 4)

**Q2. (20 points):**
- (10) First implement a sorted linked list data structure by completing the code below. This data structure should store integers in ascending order and remain sorted even when updating.
- (5) Second, write a function that takes a sorted Python list of integers and an integer, adds the integer into the list and keeps the list sorted.
- (5) Finally, generate 10,000 random integers from 1 to 1,000,000, putting one copy into a Python list and another into an instance of your SortedLinkedList class. Then compare the time it takes to insert 1,000 new random integers from the same range into the two data structures. Use time or timeit, whichever you prefer.

In [ ]:
#2
class ListNode:
    def __init__(self, value, next=None):
        self.value = value
        self.next = next

class SortedLinkedList:
    def __init__(self):
        self.head = None

    def insert(self, value):
        new_node = ListNode(value)
        if not self.head or value < self.head.value:
            new_node.next = self.head
            self.head = new_node
        else:
            if value < self.head.value:
                new_node.next = self.head
                self.head = new_node
            else:
                current = self.head
                while current.next and current.next.value < value:
                    current = current.next
                new_node.next = current.next
                current.next = new_node

    def print_list(self):
        current = self.head
        while current:
            print(current.value, end=' ')
            current = current.next

def update_sorted_python_list(sorted_list, element):
    for i in range(len(sorted_list)):
        if sorted_list[i] > element:
            sorted_list.insert(i, element)
            return
    sorted_list.append(element)  # If the element is greater than all existing elements

import time
import random

# Generating 10,000 random integers from 1 to 1,000,000
random_integers = [random.randint(1, 1000000) for _ in range(10000)]

# Copying them into a Python list and a SortedLinkedList instance
python_list = sorted(random_integers)
linked_list = SortedLinkedList()
for number in python_list:
    linked_list.insert(number)

# Generating 1,000 new random integers for insertion
new_random_integers = [random.randint(1, 1000000) for _ in range(1000)]

# Measuring the time taken to insert 1,000 integers into the Python list
start_time = time.time()
for number in new_random_integers:
    update_sorted_python_list(python_list, number)
python_list_time = time.time() - start_time

# Measuring the time taken to insert 1,000 integers into the SortedLinkedList
start_time = time.time()
for number in new_random_integers:
    linked_list.insert(number)
linked_list_time = time.time() - start_time

print(f"Time taken for Python list: {python_list_time} seconds")
print(f"Time taken for SortedLinkedList: {linked_list_time} seconds")


**Q3. (30 points):**

A(5): write code that generates a list of $n$ random numpy matrices with the following conditions:
- The matrices should have random float entries between 0 and 1.
- They should also have a random number of rows and columns between 100 and 200.
- The number of columns of the $k$th matrix should be the same as the number of rows in the $k+1$th matrix.

For example, here is an example of three valid random matrix shapes (note your matrices should be bigger, with 100-200 rows/columns), in order:
- M1 = 4x7
- M2 = 7x6
- M3 = 6x4

In [ ]:
#3a
import numpy as np
import random

def generate_random_matrices(n):
    matrices = []

    # Generate the first matrix with random dimensions
    rows = random.randint(100, 200)
    cols = random.randint(100, 200)
    first_matrix = np.random.rand(rows, cols)
    matrices.append(first_matrix)

    for i in range(1, n):
        # The number of rows for the next matrix is the number of columns of the current one
        rows = cols
        cols = random.randint(100, 200)
        next_matrix = np.random.rand(rows, cols)
        matrices.append(next_matrix)

    return matrices

# Example usage:
n = 3
random_matrices = generate_random_matrices(n)
random_matrices


[array([[0.21285052, 0.24002661, 0.25980432, ..., 0.99425074, 0.58382974,
         0.47165639],
        [0.8802695 , 0.7658106 , 0.03429246, ..., 0.45229141, 0.6433997 ,
         0.2817301 ],
        [0.7357616 , 0.469331  , 0.28758037, ..., 0.268378  , 0.11675331,
         0.68165614],
        ...,
        [0.2003385 , 0.08298138, 0.42708111, ..., 0.99767056, 0.46712963,
         0.48201199],
        [0.15396542, 0.29996355, 0.51577227, ..., 0.398777  , 0.92991607,
         0.63525341],
        [0.9671573 , 0.70072891, 0.80048291, ..., 0.85759409, 0.56485044,
         0.33032431]]),
 array([[0.50623632, 0.60255792, 0.18099484, ..., 0.43277982, 0.58596757,
         0.88259408],
        [0.42417638, 0.58902255, 0.57927212, ..., 0.38778237, 0.86525107,
         0.29017792],
        [0.03451492, 0.91891972, 0.54424022, ..., 0.44570469, 0.18567058,
         0.99032649],
        ...,
        [0.0345156 , 0.06124368, 0.24798495, ..., 0.32900653, 0.34787559,
         0.74908759],
        [0.8

B(5): write a function that calculates how many operations are needed to multiply a matrix of shape $n,m$ by one of shape $m,p$. This value is given by $m \times n \times p$.


In [ ]:
#3b
import numpy as np

def multiplication_cost(matrix1, matrix2):
    n, m = matrix1.shape
    m, p = matrix2.shape
    return n * m * p

# Example usage:
matrix1 = np.random.rand(4, 5)  # Random matrix of shape 4x5
matrix2 = np.random.rand(5, 3)  # Random matrix of shape 5x3
cost = multiplication_cost(matrix1, matrix2)
print("Number of operations needed:", cost)



Number of operations needed: 60


C(5): write a function that multiplies a list of matrices in order from left to right, returning:
- the resulting matrix product
- the sum of all the operations/costs

Remember to use np.dot to multiply matrices.

In [1]:
#3c
import numpy as np

def in_order_multiplication(list_of_matrices):
    result = list_of_matrices[0]
    total_operations = 0

    for matrix in list_of_matrices[1:]:
        result = np.dot(result, matrix)
        total_operations += result.shape[0] * result.shape[1] * matrix.shape[1]

    return result, total_operations

# Example usage:
matrix1 = np.random.rand(4, 5)  # Random matrix of shape 4x5
matrix2 = np.random.rand(5, 3)  # Random matrix of shape 5x3
matrix3 = np.random.rand(3, 2)  # Random matrix of shape 3x2

result_matrix, total_operations = in_order_multiplication([matrix1, matrix2, matrix3])
print("Resulting matrix:")
print(result_matrix)
print("Total number of operations:", total_operations)


Resulting matrix:
[[2.02793179 2.54807615]
 [2.48668151 3.14766782]
 [2.93624964 3.55234741]
 [1.20184987 1.57550199]]
Total number of operations: 52


D(10): write a function that multiplies a list of matrices in a different order. Specifically, calculate the lowest cost pair of matrices first. Then update the costs and continue. Note this is a greedy heuristic.

In [ ]:
#3d
def greedy_multiplication(list_of_matrices, total_cost=0):
    while len(list_of_matrices) > 1:
        costs = []
        for i in range(len(list_of_matrices) - 1):
            cost = multiplication_cost(list_of_matrices[i], list_of_matrices[i + 1])
            costs.append((cost, i))

        min_cost, min_index = min(costs, key=lambda x: x[0])
        total_cost += min_cost
        new_matrix = np.dot(list_of_matrices[min_index], list_of_matrices[min_index + 1])
        list_of_matrices[min_index] = new_matrix
        del list_of_matrices[min_index + 1]

    result_matrix = list_of_matrices[0]
    return result_matrix, total_cost

matrix1 = np.random.rand(4, 5)  # Random matrix of shape 4x5
matrix2 = np.random.rand(5, 3)  # Random matrix of shape 5x3
matrix3 = np.random.rand(3, 2)  # Random matrix of shape 3x2
lista = []
lista.append(matrix1)
lista.append(matrix2)
lista.append(matrix3)


greedy_multiplication(lista)


(array([[2.58022347, 1.77575059],
        [1.83379358, 1.24136669],
        [3.17288273, 2.13119703],
        [2.41253345, 1.5750859 ]]),
 70)

E(5): Generate a list of 100 random matrices using the code from part (A). Multiply them first using the functions defined in C , then again with the functions defined in D, verify that the result is the same, and report the total cost of each approach.

Hint: calculate the two products, subtract them from each other: the sum of the entries of the difference should be 0.

In [ ]:
# Generate a list of 100 random matrices
n = 100
random_matrices = generate_random_matrices(n)

# Multiply matrices using in-order multiplication
result_matrix_in_order, total_cost_in_order = in_order_multiplication(random_matrices.copy())

# Multiply matrices using greedy multiplication
result_matrix_greedy, total_cost_greedy = greedy_multiplication(random_matrices.copy())

# Verify the results are the same
difference = result_matrix_in_order - result_matrix_greedy
sum_of_difference = np.sum(np.abs(difference))

# Print the total costs and the verification result
print("Total cost (in-order multiplication):", total_cost_in_order)
print("Total cost (greedy multiplication):", total_cost_greedy)
print("Sum of the entries of the difference:", sum_of_difference)




Total cost (in-order multiplication): 420445977
Total cost (greedy multiplication): 290791624
Sum of the entries of the difference: 1.1302262669855552e+173


**Q4. (14 points):**
You are given a dataset data.csv containing sales data with the following columns: Date, Store, Product, Quantity, and Revenue. Perform the following tasks.

- Read in the dataset data.csv using Pandas.
- Using the fillna method, fill missing values with the average
- Filter the data for stores with Quantity > 10, and use the filtered dataframe for the subsequent tasks.
- Add a column: Revenue_per_unit by dividing the Revenue column by the Quantity column
- Calculate the total revenue of each store using groupby and sum

In [ ]:
import pandas as pd
#your code here

#read
df = pd.read_csv("data.csv")
#print(df)

#fill in the missing values
avg_rev = df['Revenue'].mean()

df.Revenue=df.Revenue.fillna(avg_rev)

#filtering
more10 = df[df['Quantity']>10]

#add a column
df['Revenue_per_unit']=df['Revenue']/df['Quantity']

#df.head()

#total
total = df.groupby('Store')['Revenue'].sum()

print(total)
print(df)
print(avg_rev)

FileNotFoundError: [Errno 2] No such file or directory: 'data.csv'